MQE-2305: Implement `-report-type=mftf` in magento-semver to launch MFTF SVC
magento-pangolin/magento-semver pull request #11
Opened 2020-10-08 15:31 UTC by okolesnyk

…FTF SVC

# Description (*)

## Fixed Issues (if relevant)

1. magento/magento-semver#<issue_number>: Issue title

## Manual testing scenarios (*)

1. ...

2. ...

## Questions or comments

## Contribution checklist (*)

- [ ] Pull request has a meaningful description of its purpose
- [ ] All commits are accompanied by meaningful commit messages
- [ ] All new or changed code is covered with unit/integration tests (if applicable)
- [ ] All automated tests passed successfully (all builds are green)

2020-10-08 16:09 UTC, soumyau commented on src/Scanner/ModuleNamespaceResolver.php
> +        return sprintf('%s_%s', $matches[1], $matches[2]);
this was changed to `/([\w-]*)\/Test\/Mftf/` because the old regex did not work for repositories like ASI, Inventory where modules are listed directly under root folder.

2020-10-08 16:32 UTC, okolesnyk commented on src/Scanner/ModuleNamespaceResolver.php
> +        return sprintf('%s_%s', $matches[1], $matches[2]);
Fixed, thanks!

2020-10-08 19:47 UTC, soumyau commented on src/Scanner/ModuleNamespaceResolver.php
> +        return empty($match['vendor']) ? $match['module'] : sprintf('%s_%s', $match['vendor'], $match['module']);
double check this change
ran `compare /Users/sunnikri/dev/inventory-before /Users/sunnikri/dev/inventory-after 2 --report-type=mftf` 
notice the `after_` in front of the target location. 
branch used: https://github.com/magento-tsg/inventory/tree/2.4-develop-pr43


PHP code analysis results:

Suggested semantic versioning change: NONE
```
+-------+----------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+------+
| Level | Location                                                                                                                   | Target                                                                                                                                             | Reason                  | Code |
+-------+----------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+------+
| MINOR | /Test/Mftf/Data/InventoryData.xml:0                                                                                        | after_InventoryCatalog/Data/StorefrontInventoryCatalogStockThresholdQtyDefaultConfigData                                                           | <entity> was added      | M228 |
| MINOR | /Test/Mftf/Data/InventoryData.xml:0                                                                                        | after_InventoryCatalog/Data/StorefrontInventoryCatalogStockThresholdQtyConfigData                                                                  | <entity> was added      | M228 |
| MINOR | /Test/Mftf/Data/StorefrontMessageData.xml:0                                                                                | after_InventoryCatalog/Data/ProductQtyLeft                                                                                                         | <entity> was added      | M228 |
| MINOR | /Test/Mftf/Section/StorefrontProductInfoMainSection.xml:0                                                                  | after_InventoryConfigurableProductFrontendUi/Section/StorefrontProductInfoMainSection                                                              | <section> was added     | M235 |
| MINOR | /Test/Mftf/Test/StorefrontDisplayCorrectMessageWhenChildProductSelectedForConfigProductWithTextSwatchAttributeTest.xml:0   | after_InventorySwatchesFrontendUi/Test/StorefrontDisplayCorrectMessageWhenChildProductSelectedForConfigProductWithTextSwatchAttributeTest          | <test> was added        | M237 |
| MINOR | /Test/Mftf/Test/StorefrontDisplayCorrectMessageWhenChildProductSelectedForConfigProductWithVisualSwatchAttributeTest.xml:0 | after_InventorySwatchesFrontendUi/Test/StorefrontDisplayCorrectMessageWhenChildProductSelectedForConfigProductWithVisualSwatchAttributeTest        | <test> was added        | M237 |
| MINOR | /Test/Mftf/Test/StorefrontDisplayCorrectMessageWhenChildProductSelectedForConfigProductWithDropDownAttributeTest.xml:0     | after_InventoryConfigurableProductFrontendUi/Test/StorefrontDisplayCorrectMessageWhenChildProductSelectedForConfigProductWithDropDownAttributeTest | <test> was added        | M237 |
| MINOR | /Test/Mftf/ActionGroup/AssertStorefrontConfigurableProductOptionQtyMessageActionGroup.xml:0                                | after_InventoryConfigurableProductFrontendUi/ActionGroup/AssertStorefrontConfigurableProductOptionQtyMessageActionGroup                            | <actionGroup> was added | M225 |
| MINOR | /Test/Mftf/ActionGroup/AssertStorefrontConfigurableProductOptionQtyMessageNotVisibleActionGroup.xml:0                      | after_InventoryConfigurableProductFrontendUi/ActionGroup/AssertStorefrontConfigurableProductOptionQtyMessageNotVisibleActionGroup                  | <actionGroup> was added | M225 |
+-------+----------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+------+

```

2020-10-08 19:51 UTC, soumyau commented on src/Console/Command/CompareSourceCommand.php
> +                    InputOption::VALUE_REQUIRED | InputOption::VALUE_IS_ARRAY,
this shouldn't be a required value correct? Coudn't invoke magento SVC.

2020-10-08 20:09 UTC, soumyau requested changes
Update branch with latest changes from MQE-2195.

2020-10-09 03:56 UTC, okolesnyk commented on src/Console/Command/CompareSourceCommand.php
> +                    InputOption::VALUE_REQUIRED | InputOption::VALUE_IS_ARRAY,
It can be.
I've set default value to be empty array

2020-10-09 03:57 UTC, okolesnyk commented on src/Scanner/ModuleNamespaceResolver.php
> +        return empty($match['vendor']) ? $match['module'] : sprintf('%s_%s', $match['vendor'], $match['module']);
I'll check it

2020-10-12 14:00 UTC, soumyau commented on src/Console/Command/CompareSourceCommand.php
> +                    InputOption::VALUE_REQUIRED | InputOption::VALUE_IS_ARRAY,
I see this for the above command:
```
In CompareSourceCommand.php line 237:
                                   
  Invalid report-type argument ""  
```

2020-10-12 14:02 UTC, soumyau commented on src/Console/Command/CompareSourceCommand.php
> +                    InputOption::VALUE_REQUIRED | InputOption::VALUE_IS_ARRAY,
I'm running the various report types, noticed that dbSchema changes are reported as MAJOR, whereas they don't show up at all for `--all` option. Is that expected?

Suggested version increase (based on PHP code analysis and files changed): MAJOR

PHP code analysis results:

```
Suggested semantic versioning change: MAJOR

Database (MAJOR)
+-------+------------------------------------------------+----------------------------------------------+-----------------------------------------------------------------------------------+------+
| Level | Location                                       | Target                                       | Reason                                                                            | Code |
+-------+------------------------------------------------+----------------------------------------------+-----------------------------------------------------------------------------------+------+
| MAJOR | before_InventoryShipping:0                     | before_InventoryShipping                     | Db Whitelist from module before_InventoryShipping was removed                     | M109 |
| MAJOR | before_InventorySales:0                        | before_InventorySales                        | Db Whitelist from module before_InventorySales was removed                        | M109 |
| MAJOR | before_InventoryReservations:0                 | before_InventoryReservations                 | Db Whitelist from module before_InventoryReservations was removed                 | M109 |
| MAJOR | before_InventoryLowQuantityNotification:0      | before_InventoryLowQuantityNotification      | Db Whitelist from module before_InventoryLowQuantityNotification was removed      | M109 |
| MAJOR | before_InventoryInStorePickupSales:0           | before_InventoryInStorePickupSales           | Db Whitelist from module before_InventoryInStorePickupSales was removed           | M109 |
| MAJOR | before_InventoryInStorePickupQuote:0           | before_InventoryInStorePickupQuote           | Db Whitelist from module before_InventoryInStorePickupQuote was removed           | M109 |
| MAJOR | before_InventoryInStorePickup:0                | before_InventoryInStorePickup                | Db Whitelist from module before_InventoryInStorePickup was removed                | M109 |
| MAJOR | before_InventoryDistanceBasedSourceSelection:0 | before_InventoryDistanceBasedSourceSelection | Db Whitelist from module before_InventoryDistanceBasedSourceSelection was removed | M109 |
| MAJOR | before_Inventory:0                             | before_Inventory                             | Db Whitelist from module before_Inventory was removed                             | M109 |
+-------+------------------------------------------------+----------------------------------------------+-----------------------------------------------------------------------------------+------+

Changed files:

/InventoryConfigurableProductFrontendUi/README.md
/InventoryConfigurableProductFrontendUi/registration.php
/InventoryConfigurableProductFrontendUi/composer.json
/InventoryConfigurableProductFrontendUi/Test/Mftf/Section/StorefrontProductInfoMainSection.xml
/InventoryConfigurableProductFrontendUi/Test/Mftf/Test/StorefrontDisplayCorrectMessageWhenChildProductSelectedForConfigProductWithDropDownAttributeTest.xml
/InventoryConfigurableProductFrontendUi/Test/Mftf/ActionGroup/AssertStorefrontConfigurableProductOptionQtyMessageNotVisibleActionGroup.xml
/InventoryConfigurableProductFrontendUi/Test/Mftf/ActionGroup/AssertStorefrontConfigurableProductOptionQtyMessageActionGroup.xml
/InventoryConfigurableProductFrontendUi/Plugin/ConfigurableProduct/Block/Product/View/Type/AddAdditionalInfo.php
/InventoryConfigurableProductFrontendUi/etc/module.xml
/InventoryConfigurableProductFrontendUi/etc/frontend/di.xml
/InventoryConfigurableProductFrontendUi/view/frontend/requirejs-config.js
/InventoryConfigurableProductFrontendUi/view/frontend/web/css/source/_module.less
/InventoryConfigurableProductFrontendUi/view/frontend/web/js/configurable.js
/InventoryConfigurableProductFrontendUi/view/frontend/web/js/configurable-variation-qty.js
/InventoryConfigurableProductFrontendUi/view/frontend/layout/catalog_product_view_type_configurable.xml
/InventoryConfigurableProductFrontendUi/view/frontend/templates/product/view/stockQty.phtml
/InventoryConfigurableProductFrontendUi/i18n/en_US.csv
/_metapackage/composer.json
/InventoryCatalog/Test/Mftf/Data/InventoryData.xml
/InventoryCatalog/Test/Mftf/Data/StorefrontMessageData.xml
/InventorySalesFrontendUi/composer.json
/InventorySalesFrontendUi/Plugin/Block/Stockqty/AbstractStockqtyPlugin.php
/InventoryCatalogFrontendUi/README.md
/InventoryCatalogFrontendUi/registration.php
/InventoryCatalogFrontendUi/composer.json
/InventoryCatalogFrontendUi/etc/module.xml
/InventoryCatalogFrontendUi/etc/frontend/routes.xml
/InventoryCatalogFrontendUi/Controller/Product/GetQty.php
/InventoryCatalogFrontendUi/Model/IsSalableQtyAvailableForDisplaying.php
/InventoryCatalogFrontendUi/Model/GetProductQtyLeft.php
/InventorySwatchesFrontendUi/README.md
/InventorySwatchesFrontendUi/registration.php
/InventorySwatchesFrontendUi/composer.json
/InventorySwatchesFrontendUi/Test/Mftf/Test/StorefrontDisplayCorrectMessageWhenChildProductSelectedForConfigProductWithVisualSwatchAttributeTest.xml
/InventorySwatchesFrontendUi/Test/Mftf/Test/StorefrontDisplayCorrectMessageWhenChildProductSelectedForConfigProductWithTextSwatchAttributeTest.xml
/InventorySwatchesFrontendUi/etc/module.xml
/InventorySwatchesFrontendUi/view/frontend/requirejs-config.js
/InventorySwatchesFrontendUi/view/frontend/web/js/swatch-renderer.js

```

2020-10-12 14:09 UTC, soumyau commented on src/ReportBuilder.php
> +    protected $availableAnalyzerFactoryClasses = [
I'm running the various report types, noticed that dbSchema changes are reported as MAJOR, whereas they don't show up at all for `--all` option. Is that expected?

`compare /Users/sunnikri/dev/inventory-before /Users/sunnikri/dev/inventory-after  --report-type=dbSchema`

Suggested version increase (based on PHP code analysis and files changed): MAJOR

PHP code analysis results:

```
Suggested semantic versioning change: MAJOR

Database (MAJOR)
+-------+------------------------------------------------+----------------------------------------------+-----------------------------------------------------------------------------------+------+
| Level | Location                                       | Target                                       | Reason                                                                            | Code |
+-------+------------------------------------------------+----------------------------------------------+-----------------------------------------------------------------------------------+------+
| MAJOR | before_InventoryShipping:0                     | before_InventoryShipping                     | Db Whitelist from module before_InventoryShipping was removed                     | M109 |
| MAJOR | before_InventorySales:0                        | before_InventorySales                        | Db Whitelist from module before_InventorySales was removed                        | M109 |
| MAJOR | before_InventoryReservations:0                 | before_InventoryReservations                 | Db Whitelist from module before_InventoryReservations was removed                 | M109 |
| MAJOR | before_InventoryLowQuantityNotification:0      | before_InventoryLowQuantityNotification      | Db Whitelist from module before_InventoryLowQuantityNotification was removed      | M109 |
| MAJOR | before_InventoryInStorePickupSales:0           | before_InventoryInStorePickupSales           | Db Whitelist from module before_InventoryInStorePickupSales was removed           | M109 |
| MAJOR | before_InventoryInStorePickupQuote:0           | before_InventoryInStorePickupQuote           | Db Whitelist from module before_InventoryInStorePickupQuote was removed           | M109 |
| MAJOR | before_InventoryInStorePickup:0                | before_InventoryInStorePickup                | Db Whitelist from module before_InventoryInStorePickup was removed                | M109 |
| MAJOR | before_InventoryDistanceBasedSourceSelection:0 | before_InventoryDistanceBasedSourceSelection | Db Whitelist from module before_InventoryDistanceBasedSourceSelection was removed | M109 |
| MAJOR | before_Inventory:0                             | before_Inventory                             | Db Whitelist from module before_Inventory was removed                             | M109 |
+-------+------------------------------------------------+----------------------------------------------+-----------------------------------------------------------------------------------+------+

Changed files:

/InventoryConfigurableProductFrontendUi/README.md
/InventoryConfigurableProductFrontendUi/registration.php
/InventoryConfigurableProductFrontendUi/composer.json
/InventoryConfigurableProductFrontendUi/Test/Mftf/Section/StorefrontProductInfoMainSection.xml
/InventoryConfigurableProductFrontendUi/Test/Mftf/Test/StorefrontDisplayCorrectMessageWhenChildProductSelectedForConfigProductWithDropDownAttributeTest.xml
/InventoryConfigurableProductFrontendUi/Test/Mftf/ActionGroup/AssertStorefrontConfigurableProductOptionQtyMessageNotVisibleActionGroup.xml
/InventoryConfigurableProductFrontendUi/Test/Mftf/ActionGroup/AssertStorefrontConfigurableProductOptionQtyMessageActionGroup.xml
/InventoryConfigurableProductFrontendUi/Plugin/ConfigurableProduct/Block/Product/View/Type/AddAdditionalInfo.php
/InventoryConfigurableProductFrontendUi/etc/module.xml
/InventoryConfigurableProductFrontendUi/etc/frontend/di.xml
/InventoryConfigurableProductFrontendUi/view/frontend/requirejs-config.js
/InventoryConfigurableProductFrontendUi/view/frontend/web/css/source/_module.less
/InventoryConfigurableProductFrontendUi/view/frontend/web/js/configurable.js
/InventoryConfigurableProductFrontendUi/view/frontend/web/js/configurable-variation-qty.js
/InventoryConfigurableProductFrontendUi/view/frontend/layout/catalog_product_view_type_configurable.xml
/InventoryConfigurableProductFrontendUi/view/frontend/templates/product/view/stockQty.phtml
/InventoryConfigurableProductFrontendUi/i18n/en_US.csv
/_metapackage/composer.json
/InventoryCatalog/Test/Mftf/Data/InventoryData.xml
/InventoryCatalog/Test/Mftf/Data/StorefrontMessageData.xml
/InventorySalesFrontendUi/composer.json
/InventorySalesFrontendUi/Plugin/Block/Stockqty/AbstractStockqtyPlugin.php
/InventoryCatalogFrontendUi/README.md
/InventoryCatalogFrontendUi/registration.php
/InventoryCatalogFrontendUi/composer.json
/InventoryCatalogFrontendUi/etc/module.xml
/InventoryCatalogFrontendUi/etc/frontend/routes.xml
/InventoryCatalogFrontendUi/Controller/Product/GetQty.php
/InventoryCatalogFrontendUi/Model/IsSalableQtyAvailableForDisplaying.php
/InventoryCatalogFrontendUi/Model/GetProductQtyLeft.php
/InventorySwatchesFrontendUi/README.md
/InventorySwatchesFrontendUi/registration.php
/InventorySwatchesFrontendUi/composer.json
/InventorySwatchesFrontendUi/Test/Mftf/Test/StorefrontDisplayCorrectMessageWhenChildProductSelectedForConfigProductWithVisualSwatchAttributeTest.xml
/InventorySwatchesFrontendUi/Test/Mftf/Test/StorefrontDisplayCorrectMessageWhenChildProductSelectedForConfigProductWithTextSwatchAttributeTest.xml
/InventorySwatchesFrontendUi/etc/module.xml
/InventorySwatchesFrontendUi/view/frontend/requirejs-config.js
/InventorySwatchesFrontendUi/view/frontend/web/js/swatch-renderer.js

```

2020-10-12 14:46 UTC, okolesnyk commented on src/Console/Command/CompareSourceCommand.php
> +                    InputOption::VALUE_REQUIRED | InputOption::VALUE_IS_ARRAY,
Yep, my bad. Validation method makes it happen. 
Fixed

2020-10-12 14:52 UTC, okolesnyk commented on src/ReportBuilder.php
> +    protected $availableAnalyzerFactoryClasses = [
`all` option is weird 
It doesn't mean that `all` analyzers will be triggered, it means all default PHP analyzers will be triggered. It is confusing and it's beed forever in SVC tool this way, so I'm not gonna solve this in scope of our ticket.

Basic flows:
If you want to run all analyzers including mftf you need to specify them like this:
`--report-type=all --report-type=api --report-type=dbSchema --report-type=diXml --report-type=layout --report-type=systemXml --report-type=xsd --report-type=less --report-type=mftf`

2020-10-13 15:51 UTC, soumyau approved these changes

2020-10-13 16:28 UTC, merged